### ISSUE TITLE
User details (userId and userName) returned by two authservice Userdetails utility APIs are different

### ISSUE THREAD

**Issue by yasima-csiro** [AtlasOfLivingAustralia/ala-security-project#48]
Issue in Username and UserId mapping.

<img width="628" alt="image" src="https://github.com/user-attachments/assets/1ca72227-fe57-45ca-8748-55066d9efecb">
<img width="633" alt="image" src="https://github.com/user-attachments/assets/51a0fe9a-59aa-4058-a490-b89d2ffcd6fc">

**Comment by yasima-csiro** [comment]
This issue was fixed after setting up following missing config.


```
security:
    oidc:
        alaUseridClaim: username
        userNameClaim: email
```
